global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "aiops-engine"
    metrics_path: /metrics
    static_configs:
      - targets: ["127.0.0.1:7000"]
  - job_name: "kitchen-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["127.0.0.1:5101"]
 